
const languages = {
  en: { name: 'English', nativeName: 'English', rtl: false },
  es: { name: 'Spanish', nativeName: 'Español', rtl: false },
  fr: { name: 'French', nativeName: 'Français', rtl: false },
  de: { name: 'German', nativeName: 'Deutsch', rtl: false },
  zh: { name: 'Chinese', nativeName: '中文', rtl: false },
  ar: { name: 'Arabic', nativeName: 'العربية', rtl: true },
  hi: { name: 'Hindi', nativeName: 'हिन्दी', rtl: false },
  pt: { name: 'Portuguese', nativeName: 'Português', rtl: false },
  ru: { name: 'Russian', nativeName: 'Русский', rtl: false },
  ja: { name: 'Japanese', nativeName: '日本語', rtl: false },
  ko: { name: 'Korean', nativeName: '한국어', rtl: false },
  it: { name: 'Italian', nativeName: 'Italiano', rtl: false },
  nl: { name: 'Dutch', nativeName: 'Nederlands', rtl: false },
  tr: { name: 'Turkish', nativeName: 'Türkçe', rtl: false },
  pl: { name: 'Polish', nativeName: 'Polski', rtl: false },
  vi: { name: 'Vietnamese', nativeName: 'Tiếng Việt', rtl: false },
  th: { name: 'Thai', nativeName: 'ไทย', rtl: false },
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia', rtl: false },
  ms: { name: 'Malay', nativeName: 'Bahasa Melayu', rtl: false },
  fil: { name: 'Filipino', nativeName: 'Filipino', rtl: false },
  sw: { name: 'Swahili', nativeName: 'Kiswahili', rtl: false },
  ha: { name: 'Hausa', nativeName: 'Hausa', rtl: false },
  yo: { name: 'Yoruba', nativeName: 'Yorùbá', rtl: false },
  ig: { name: 'Igbo', nativeName: 'Igbo', rtl: false },
  am: { name: 'Amharic', nativeName: 'አማርኛ', rtl: false },
  om: { name: 'Oromo', nativeName: 'Afaan Oromoo', rtl: false },
  so: { name: 'Somali', nativeName: 'Soomaali', rtl: false },
  rw: { name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', rtl: false },
  zu: { name: 'Zulu', nativeName: 'isiZulu', rtl: false },
  xh: { name: 'Xhosa', nativeName: 'isiXhosa', rtl: false },
  st: { name: 'Sesotho', nativeName: 'Sesotho', rtl: false },
  tn: { name: 'Setswana', nativeName: 'Setswana', rtl: false },
  sn: { name: 'Shona', nativeName: 'chiShona', rtl: false },
  ny: { name: 'Chichewa', nativeName: 'Chichewa', rtl: false },
  mg: { name: 'Malagasy', nativeName: 'Malagasy', rtl: false },
  bn: { name: 'Bengali', nativeName: 'বাংলা', rtl: false },
  ta: { name: 'Tamil', nativeName: 'தமிழ்', rtl: false },
  te: { name: 'Telugu', nativeName: 'తెలుగు', rtl: false },
  mr: { name: 'Marathi', nativeName: 'मराठी', rtl: false },
  ur: { name: 'Urdu', nativeName: 'اردو', rtl: true },
  pa: { name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', rtl: false },
  gu: { name: 'Gujarati', nativeName: 'ગુજરાતી', rtl: false },
  kn: { name: 'Kannada', nativeName: 'ಕನ್ನಡ', rtl: false },
  ml: { name: 'Malayalam', nativeName: 'മലയാളം', rtl: false },
  si: { name: 'Sinhala', nativeName: 'සිංහල', rtl: false },
  ne: { name: 'Nepali', nativeName: 'नेपाली', rtl: false },
  my: { name: 'Burmese', nativeName: 'မြန်မာ', rtl: false },
  km: { name: 'Khmer', nativeName: 'ខ្មែរ', rtl: false },
  lo: { name: 'Lao', nativeName: 'ລາວ', rtl: false },
  ka: { name: 'Georgian', nativeName: 'ქართული', rtl: false },
  hy: { name: 'Armenian', nativeName: 'Հայերեն', rtl: false },
  az: { name: 'Azerbaijani', nativeName: 'Azərbaycan', rtl: false },
  uz: { name: 'Uzbek', nativeName: 'Oʻzbek', rtl: false },
  kk: { name: 'Kazakh', nativeName: 'Қазақ', rtl: false },
  ky: { name: 'Kyrgyz', nativeName: 'Кыргызча', rtl: false },
  tg: { name: 'Tajik', nativeName: 'Тоҷикӣ', rtl: false },
  tk: { name: 'Turkmen', nativeName: 'Türkmen', rtl: false },
  mn: { name: 'Mongolian', nativeName: 'Монгол', rtl: false },
  bo: { name: 'Tibetan', nativeName: 'བོད་ཡིག', rtl: false },
  dz: { name: 'Dzongkha', nativeName: 'རྫོང་ཁ', rtl: false },
  fa: { name: 'Persian', nativeName: 'فارسی', rtl: true },
  ps: { name: 'Pashto', nativeName: 'پښتو', rtl: true },
  ku: { name: 'Kurdish', nativeName: 'Kurdî', rtl: true },
  he: { name: 'Hebrew', nativeName: 'עברית', rtl: true },
  yi: { name: 'Yiddish', nativeName: 'ייִדיש', rtl: true },
  uk: { name: 'Ukrainian', nativeName: 'Українська', rtl: false },
  be: { name: 'Belarusian', nativeName: 'Беларуская', rtl: false },
  bg: { name: 'Bulgarian', nativeName: 'Български', rtl: false },
  mk: { name: 'Macedonian', nativeName: 'Македонски', rtl: false },
  sr: { name: 'Serbian', nativeName: 'Српски', rtl: false },
  hr: { name: 'Croatian', nativeName: 'Hrvatski', rtl: false },
  bs: { name: 'Bosnian', nativeName: 'Bosanski', rtl: false },
  sl: { name: 'Slovenian', nativeName: 'Slovenščina', rtl: false },
  sk: { name: 'Slovak', nativeName: 'Slovenčina', rtl: false },
  cs: { name: 'Czech', nativeName: 'Čeština', rtl: false },
  ro: { name: 'Romanian', nativeName: 'Română', rtl: false },
  hu: { name: 'Hungarian', nativeName: 'Magyar', rtl: false },
  fi: { name: 'Finnish', nativeName: 'Suomi', rtl: false },
  et: { name: 'Estonian', nativeName: 'Eesti', rtl: false },
  lv: { name: 'Latvian', nativeName: 'Latviešu', rtl: false },
  lt: { name: 'Lithuanian', nativeName: 'Lietuvių', rtl: false },
  sq: { name: 'Albanian', nativeName: 'Shqip', rtl: false },
  mt: { name: 'Maltese', nativeName: 'Malti', rtl: false },
  ga: { name: 'Irish', nativeName: 'Gaeilge', rtl: false },
  cy: { name: 'Welsh', nativeName: 'Cymraeg', rtl: false },
  gd: { name: 'Scottish Gaelic', nativeName: 'Gàidhlig', rtl: false },
  is: { name: 'Icelandic', nativeName: 'Íslenska', rtl: false },
  fo: { name: 'Faroese', nativeName: 'Føroyskt', rtl: false },
  da: { name: 'Danish', nativeName: 'Dansk', rtl: false },
  no: { name: 'Norwegian', nativeName: 'Norsk', rtl: false },
  sv: { name: 'Swedish', nativeName: 'Svenska', rtl: false },
  af: { name: 'Afrikaans', nativeName: 'Afrikaans', rtl: false }
};

module.exports = languages;
